ollama_path: "C:/Users/AngelicaChowdhury/AppData/Local/Programs/Ollama/ollama.exe"
model_name: "llama3:8b"
embedding_model: "sentence-transformers/all-MiniLM-L6-v2"
chunk_size: 1000
chunk_overlap: 100
file_path: "data/processed/combined_content.txt"